export {DarkMode} from "./darkMode/DarkMode"
export {Header} from "./Header/Header"
export {Footer} from "./footer/Footer"
//info
export {Intro} from "./info/Intro"
export {Color} from "./info/Color"
export {Favicon} from "./info/Favicon"
export {Letra} from "./info/Letra"
export {Layaout} from "./info/Layaout"
export {Idioma} from "./info/Idioma"
export {Css} from "./info/Css"
export {Ceo} from "./info/Ceo"
export {HeaderT} from "./info/Header"
export {DarkModeT} from "./info/DarkMode"
export {FooterT} from "./info/Footer"
export {Remate} from "./info/Remate"
export {Clipboard} from "./clipboard/Clipboard"
