export {DarkMode} from "./darkMode/DarkMode"
export {Header} from "./Header/Header"
export {Footer} from "./footer/Footer"
//info
export {Intro} from "./info/Intro"
export {Color} from "./info/Color"
export {Favicon} from "./info/Favicon"
export {Letra} from "./info/Letra"
export {Layaout} from "./info/Layaout"
export {Idioma} from "./info/Idioma"
export {Clipboard} from "./clipboard/Clipboard"
